Introduced a condition in line 22 of .github/workflows/test-runner.yaml to check for docker before installation

diff --git a/.github/workflows/test-runner.yaml b/.github/workflows/test-runner.yaml
--- a/.github/workflows/test-runner.yaml
+++ b/.github/workflows/test-runner.yaml
@@ -17,24 +17,30 @@ jobs:
       - name: Check working directory
         run: pwd
 
-      # - name: Install Docker
-      #   run: |
-      #     sudo apt-get update -y &&
-      #     sudo apt-get install -y ca-certificates curl gnupg &&
-      #     sudo install -m 0755 -d /etc/apt/keyrings &&
-      #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg &&
-      #     sudo chmod a+r /etc/apt/keyrings/docker.gpg &&
-      #     echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&
-      #     sudo apt-get update -y &&
-      #     sudo apt-get install -y docker-ce docker-ce-cli containerd.io &&
-      #     sudo systemctl start docker &&
-      #     sudo systemctl enable docker
+      - name: Install Docker if not present
+        run: |
+          if ! command -v docker &> /dev/null
+          then
+            echo "Docker not found, installing..."
+            sudo apt-get update -y &&
+            sudo apt-get install -y ca-certificates curl gnupg &&
+            sudo install -m 0755 -d /etc/apt/keyrings &&
+            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg &&
+            sudo chmod a+r /etc/apt/keyrings/docker.gpg &&
+            echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null &&
+            sudo apt-get update -y &&
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io &&
+            sudo systemctl start docker &&
+            sudo systemctl enable docker
+          else
+            echo "Docker is already installed"
+          fi
 
       - name: Check Docker version
-        run:  docker --version
+        run: docker --version
 
       - name: Check containers
-        run:  sudo docker ps -a
+        run: sudo docker ps -a
 
       - name: Check running docker services
         run: sudo docker ps
@@ -50,6 +56,6 @@ jobs:
 
       - name: Run the Docker Container
         run: sudo docker run -d --name csn-nginx -p 8080:80 csn-nginx
-    
+
       - name: Test the web service
         run: curl http://localhost:8080
